// workshops types
export const GET_WORKSHOPS_REQUEST = 'GET_WORKSHOPS_REQUEST';
export const GET_WORKSHOPS_SUCCESS = 'GET_WORKSHOPS_SUCCESS';
export const GET_WORKSHOPS_FAILURE = 'GET_WORKSHOPS_FAILURE';
export const GET_FILTERED_WORKSHOPS = 'GET_FILTERED_WORKSHOPS';
export const GET_SIMILAR_WORKSHOPS = 'GET_SIMILAR_WORKSHOPS';

// users types
export const GET_WORKSHOP_USER_REQUEST = 'GET_WORKSHOP_USER_REQUEST';
export const GET_WORKSHOP_USER_SUCCESS = 'GET_WORKSHOP_USER_SUCCESS';
export const GET_WORKSHOP_USER_FAILURE = 'GET_WORKSHOP_USER_FAILURE';

// filters types
export const APPLY_FILTER = 'APPLY_FILTER';

// checkout types
export const ADD_TO_CART = 'ADD_TO_CART';
export const OPEN_CHECKOUT_CART = 'OPEN_CHECKOUT_CART';
export const CLOSE_CHECKOUT_CART = 'CLOSE_CHECKOUT_CART';
export const UPDATE_NUMBER_OF_TICKETS = 'UPDATE_NUMBER_OF_TICKETS';
export const DELETE_CHECKOUT_ITEM = 'DELETE_CHECKOUT_ITEM';
export const OPEN_CHECKOUT_MODAL = 'OPEN_CHECKOUT_MODAL';
export const CLOSE_CHECKOUT_MODAL = 'CLOSE_CHECKOUT_MODAL';
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILURE = 'ORDER_FAILURE';
